import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const deploymentsDir = path.join(root, "deployments", "sepolia");
const source = path.join(deploymentsDir, "FHEAuction.json");
const outDir = path.join(root, "home", "src");
const outFile = path.join(outDir, "abi.ts");

function main() {
  if (!fs.existsSync(source)) {
    throw new Error(`Missing deployments artifact: ${source}. Deploy to sepolia first.`);
  }
  const raw = JSON.parse(fs.readFileSync(source, "utf-8"));
  const { address, abi } = raw;
  if (!address || !abi) throw new Error("Invalid deployment file: missing address or abi");
  fs.mkdirSync(outDir, { recursive: true });
  const content = `// AUTO-GENERATED by scripts/sync-abi.ts. Do not edit.
export const FHE_AUCTION_ADDRESS = "${address}" as const;
export const FHE_AUCTION_ABI = ${JSON.stringify(abi, null, 2)} as const;
`;
  fs.writeFileSync(outFile, content, "utf-8");
  console.log(`Wrote ${outFile}`);
}

main();

